version: 2.1
orbs:
  pipenv: frameio/pipenv@0.17.3
executors:
  pipenv/python:
    tag: 3.6
workflows:
  buildAndTest:
    jobs:
      - pipenv/install:
          args: -d
      - pipenv/shell:
          args: python -m flake8
          requires:
            - pipenv/install
