version: 2.1
orbs:
  pipenv: frameio/pipenv@0.17.3
jobs:
  buildAndTest:
    executor: << parameters.e >>
    parameters:
      e:
        type: executor
    steps:
      - checkout
      - pipenv/install:
          args: -d --ignore-pipfile
      - pipenv/shell:
          args: python -m flake8
workflows:
  buildAndTest:
    jobs:
      - buildAndTest:
          e:
            name: pipenv/python
            tag: "3.6"
