version: 2.1
orbs:
  pipenv: frameio/pipenv@0.17.3
workflows:
  buildAndTest:
    jobs:
      - pipenv/install:
          args: -d
      - pipenv/shell:
          args: python -m flake8
          requires:
            - pipenv/build
